title: "Munmun Shrestha"
email: munmunshrestha1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Women in Tech.
baseurl: "/" 
url: "https://munmunshrestha.github.io/" 
twitter_username: munmunshrestha
github_username:  munmunshrestha

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
